version: '3.8'

services:
  burnly-db:
    image: postgres:17-alpine
    container_name: burnly-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: burnly
    ports:
      - '5432:5432'
    volumes:
      - burnly-db-data:/var/lib/postgresql/data

volumes:
  burnly-db-data:
