import { SimulationInput } from '@/types/simulation';

export const PRESET_SCENARIOS: SimulationInput[] = [
  {
    id: 'seed-saas-standard',
    scenarioName: 'Seed SaaS (Standard)',
    investmentAmount: 1000000,
    existingCash: 100000,
    currentMonthlyRevenue: 15000,
    businessModel: 'SaaS',
    monthlyGrowthRate: 10,
    grossMargin: 80,
    cac: 600,
    churnRate: 2,
    marketingSpend: 12000,
    infraSpend: 3000,
    opsSpend: 5000,
    founderSalary: 10000,
    projectionMonths: 36,
    plannedHires: [
      { id: 'h1', role: 'Sr. Software Engineer', monthlySalary: 10000, startMonth: 2 },
      { id: 'h2', role: 'Product Designer', monthlySalary: 8000, startMonth: 3 },
      { id: 'h3', role: 'Growth Marketer', monthlySalary: 9000, startMonth: 4 },
    ],
  },
  {
    id: 'aggressive-scaleup',
    scenarioName: 'Aggressive Scale-up',
    investmentAmount: 1500000,
    existingCash: 50000,
    currentMonthlyRevenue: 20000,
    businessModel: 'SaaS',
    monthlyGrowthRate: 15,
    grossMargin: 75,
    cac: 1200,
    churnRate: 4,
    marketingSpend: 45000,
    infraSpend: 8000,
    opsSpend: 10000,
    founderSalary: 15000,
    projectionMonths: 36,
    plannedHires: [
      { id: 'ah1', role: 'VP of Sales', monthlySalary: 16000, startMonth: 1 },
      { id: 'ah2', role: 'Staff Backend Engineer', monthlySalary: 13000, startMonth: 1 },
      { id: 'ah3', role: 'Frontend Lead', monthlySalary: 12000, startMonth: 1 },
      { id: 'ah4', role: 'SDR 1', monthlySalary: 7000, startMonth: 2 },
      { id: 'ah5', role: 'DevOps Specialist', monthlySalary: 11000, startMonth: 2 },
    ],
  },
  {
    id: 'lean-bootstrapper',
    scenarioName: 'Lean Bootstrapper',
    investmentAmount: 250000,
    existingCash: 50000,
    currentMonthlyRevenue: 8000,
    businessModel: 'SaaS',
    monthlyGrowthRate: 8,
    grossMargin: 85,
    cac: 300,
    churnRate: 1.5,
    marketingSpend: 3000,
    infraSpend: 1000,
    opsSpend: 2000,
    founderSalary: 6000,
    projectionMonths: 36,
    plannedHires: [
      { id: 'lh1', role: 'Full-stack Developer', monthlySalary: 7000, startMonth: 5 },
    ],
  },
  {
    id: 'd2c-brand',
    scenarioName: 'D2C Consumer Brand',
    investmentAmount: 500000,
    existingCash: 20000,
    currentMonthlyRevenue: 25000,
    businessModel: 'D2C',
    monthlyGrowthRate: 12,
    grossMargin: 55,
    cac: 45,
    churnRate: 5,
    marketingSpend: 22000,
    infraSpend: 2000,
    opsSpend: 6000,
    founderSalary: 8000,
    projectionMonths: 36,
    plannedHires: [
      { id: 'dh1', role: 'Supply Chain Lead', monthlySalary: 7000, startMonth: 2 },
      { id: 'dh2', role: 'Social Media Marketer', monthlySalary: 5500, startMonth: 3 },
    ],
  },
];
